name: .NET Core

on: [push,  pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v1
- name: Setup .NET Core
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 2.1.802 <- ---- https://github.com/ISUCT/Tprogramming_2021/pull/5/files
- name: Build with dotnet
  run: |
    cd CourseApp 
    dotnet build --configuration Release
- name: Run tests
  run: |
    cd CourseApp.Tests
    dotnet test

